name: 'Dependabot Automerge - Action'

on:
  pull_request_target:

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: WyriHaximus/github-action-wait-for-status@v1.2.0
        with:
          ignoreActions: worker,WIP
          checkInterval: 300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: 'wait run audit'
        uses: oke-py/npm-audit-action@v1.7.4
        if: steps.waitforstatuschecks.outputs.status == 'success'
        id: waitrunaudit
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true

      - name: 'Auto merge'
        uses: actions/github-script@v5
        if: steps.waitrunaudit.npm_audit.status == 0
        with:
          github-token: ${{github.token}}
          script: |
            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.rest.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
